# arguments for dataset
dataset: pascal
nclass: 21
crop_size: 321
data_root: your/pascal/path

# arguments for training
epochs: 80
batch_size: 2
lr: 0.001  # 4GPUs
lr_multi: 10.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95

# arguments for model
backbone: resnet101
multi_grid: False
replace_stride_with_dilation: [False, False, True]
dilations: [6, 12, 18]

# AOS
iou_samp: True
# ACT
conf_thre: True
# segformer 
use_segformer: False
